import { createTimeline, type Timeline } from "animejs";
import { inject, onBeforeUnmount, onMounted, type InjectionKey, type Ref } from "vue";

// A scene is an SVG component with one anime.js timeline. Each main step ends with
// `tl.label("s1")`, `tl.label("s2")`, …; StepAnim plays the timeline to that label when
// the matching bullet or [anim] line of the slide appears. Initial states belong in the
// template (style="opacity: 0"), the tweens below give explicit [from, to] values so
// seeking backwards restores them.

export const SCENE_TIMELINE: InjectionKey<(timeline: Timeline) => void> = Symbol("scene-timeline");

// Scene elements are named with data-part="…" rather than classes: class names like
// `answer` or `prompt` are already styled by the deck or generated by UnoCSS.
// q("prompt blank") returns every element carrying one of these parts.
export type SceneQuery = (parts: string) => Element[];

export function useSceneTimeline(root: Readonly<Ref<Element | null>>, build: (tl: Timeline, q: SceneQuery) => void) {
  const register = inject(SCENE_TIMELINE, undefined);
  let timeline: Timeline | undefined;

  onMounted(() => {
    const el = root.value;
    if (!el) return;
    const q: SceneQuery = (parts) => [...el.querySelectorAll(parts.trim().split(/\s+/).map((part) => `[data-part~="${part}"]`).join(","))];
    timeline = createTimeline({ autoplay: false, defaults: { duration: 500, ease: "inOutQuad", composition: "none" } });
    build(timeline, q);
    register?.(timeline);
  });

  onBeforeUnmount(() => timeline?.revert());
}

// Motion presets, named after their Manim counterparts.
export const fadeIn = (extra: Record<string, unknown> = {}) => ({ opacity: [0, 1], duration: 400, ...extra });
export const fadeOut = (extra: Record<string, unknown> = {}) => ({ opacity: [1, 0], duration: 300, ...extra });
// GrowFromEdge(LEFT): scales from the left edge of the element's box.
export const growFromLeft = (to = 1, extra: Record<string, unknown> = {}) => ({ scaleX: [0, to], duration: 600, ...extra });
// FadeIn(shift=…): fades in while sliding into place. translateX/Y, not x/y: on SVG
// elements with x/y attributes (text, rect) anime.js would animate the attributes instead.
export const slideIn = (dx = -12, dy = 0, extra: Record<string, unknown> = {}) => ({
  opacity: [0, 1],
  translateX: [dx, 0],
  translateY: [dy, 0],
  duration: 400,
  ...extra,
});
